// Generated by scripts/generate-tsrx-types.mjs.
import type { HtmlComponentMap, StreamingComponentMap } from '../customComponents';
import type { NodeRendererProps } from '../types';
export declare function NodeRenderer<TStreamingComponents extends StreamingComponentMap = StreamingComponentMap, THtmlComponents extends Record<string, any> = HtmlComponentMap>(rawProps: NodeRendererProps<TStreamingComponents, THtmlComponents>): import("octane/jsx-runtime").Octane.JSX.Element;
export default NodeRenderer;
