// Generated by scripts/generate-tsrx-types.mjs.
import type { ParsedNode } from 'stream-markdown-parser';
import type { NodeComponentProps } from '../../types/node-component';
export declare function BlockquoteNode(props: NodeComponentProps<{
    type: 'blockquote';
    children?: ParsedNode[];
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export default BlockquoteNode;
