// Generated by scripts/generate-tsrx-types.mjs.
import type { ShikiCodeBlockProps } from '../../types/component-props';
export interface MarkdownCodeBlockNodeProps extends ShikiCodeBlockProps {
    node: {
        type: 'code_block';
        language: string;
        code: string;
        raw: string;
        diff?: boolean;
        originalCode?: string;
        updatedCode?: string;
    };
    loading?: boolean;
    stream?: boolean;
    darkTheme?: string;
    lightTheme?: string;
    isDark?: boolean;
    isShowPreview?: boolean;
    enableFontSizeControl?: boolean;
    minWidth?: string | number;
    maxWidth?: string | number;
    showPreviewButton?: boolean;
    showCollapseButton?: boolean;
    showFontSizeButtons?: boolean;
    showTooltips?: boolean;
    onCopy?: (code: string) => void;
    onPreviewCode?: (payload: {
        type: string;
        content: string;
        title: string;
    }) => void;
}
export declare function MarkdownCodeBlockNode(rawProps: MarkdownCodeBlockNodeProps): import("octane/jsx-runtime").Octane.JSX.Element;
export default MarkdownCodeBlockNode;
