// Generated by scripts/generate-tsrx-types.mjs.
import type { NodeComponentProps } from '../../types/node-component';
export declare function SuperscriptNode(props: NodeComponentProps<{
    type: 'superscript';
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export default SuperscriptNode;
