// Generated by scripts/generate-tsrx-types.mjs.
import type { NodeComponentProps } from '../../types/node-component';
export declare function InlineCodeNode(props: NodeComponentProps<{
    type: 'inline_code';
    code: string;
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export default InlineCodeNode;
