// Generated by scripts/generate-tsrx-types.mjs.
import type { DefinitionItemNode } from 'stream-markdown-parser';
import type { NodeComponentProps } from '../../types/node-component';
export declare function DefinitionListNode(props: NodeComponentProps<{
    type: 'definition_list';
    items?: DefinitionItemNode[];
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export default DefinitionListNode;
