// Generated by scripts/generate-tsrx-types.mjs.
import type { NodeComponentProps } from '../../types/node-component';
export interface ReferenceNodeHandlers {
    onClick?: (event: MouseEvent, id: string, messageId?: string, threadId?: string) => void;
    onMouseEnter?: (event: MouseEvent, id: string, messageId?: string, threadId?: string) => void;
    onMouseLeave?: (event: MouseEvent, id: string, messageId?: string, threadId?: string) => void;
}
export declare function ReferenceNode(props: NodeComponentProps<{
    type: 'reference';
    id: string;
}> & {
    messageId?: string;
    threadId?: string;
} & ReferenceNodeHandlers): import("octane/jsx-runtime").Octane.JSX.Element;
export default ReferenceNode;
