// Generated by scripts/generate-tsrx-types.mjs.
import type { NodeComponentProps } from '../../types/node-component';
export declare function FootnoteReferenceNode(props: NodeComponentProps<{
    type: 'footnote_reference';
    id: string;
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export default FootnoteReferenceNode;
