// Generated by scripts/generate-tsrx-types.mjs.
import type { NodeComponentProps } from '../../types/node-component';
export declare function TextNode(props: NodeComponentProps<{
    type: 'text';
    content: string;
    center?: boolean;
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export default TextNode;
