// Generated by scripts/generate-tsrx-types.mjs.
import type { NodeComponentProps } from '../../types/node-component';
export declare function InsertNode(props: NodeComponentProps<{
    type: 'insert';
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export default InsertNode;
