// Generated by scripts/generate-tsrx-types.mjs.
import type { NodeComponentProps } from '../../types/node-component';
export declare function CheckboxNode(props: NodeComponentProps<{
    type: 'checkbox' | 'checkbox_input';
    checked?: boolean;
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export default CheckboxNode;
