// Generated by scripts/generate-tsrx-types.mjs.
import type { NodeComponentProps } from '../../types/node-component';
export declare function SubscriptNode(props: NodeComponentProps<{
    type: 'subscript';
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export default SubscriptNode;
