// Generated by scripts/generate-tsrx-types.mjs.
import type { MathInlineNodeProps } from '../../types/component-props';
export declare function MathInlineNode({ node }: MathInlineNodeProps): import("octane/jsx-runtime").Octane.JSX.Element;
