// Generated by scripts/generate-tsrx-types.mjs.
import type { MathBlockNodeProps } from '../../types/component-props';
export declare function MathBlockNode({ node }: MathBlockNodeProps): import("octane/jsx-runtime").Octane.JSX.Element;
