// Generated by scripts/generate-tsrx-types.mjs.
import type { ParsedNode } from 'stream-markdown-parser';
import type { NodeComponentProps } from '../../types/node-component';
export declare function VmrContainerNode(props: NodeComponentProps<{
    type: 'vmr_container';
    name: string;
    attrs?: Record<string, string> | [string, string | null][] | null;
    children?: ParsedNode[];
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export default VmrContainerNode;
