// Generated by scripts/generate-tsrx-types.mjs.
import type { HtmlPolicy, ParsedNode } from 'stream-markdown-parser';
import type { CustomComponentMap } from '../../customComponents';
import type { NodeComponentProps } from '../../types/node-component';
import * as Octane from 'octane';
export declare function HtmlBlockNode(props: NodeComponentProps<{
    type: 'html_block';
    content: string;
    raw?: string;
    tag?: string;
    attrs?: [string, string | null][] | null;
    children?: ParsedNode[];
    loading?: boolean;
}> & {
    customComponents?: CustomComponentMap;
    htmlPolicy?: HtmlPolicy;
    placeholder?: Octane.OctaneNode;
}): Octane.ElementDescriptor<any>;
export default HtmlBlockNode;
