// Generated by scripts/generate-tsrx-types.mjs.
import type { ListItemNode as ParsedListItemNode } from 'stream-markdown-parser';
import type { NodeComponentProps } from '../../types/node-component';
export declare function ListNode(props: NodeComponentProps<{
    type: 'list';
    ordered?: boolean;
    start?: number;
    items?: ParsedListItemNode[];
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export default ListNode;
