// Generated by scripts/generate-tsrx-types.mjs.
import type { ParsedNode } from 'stream-markdown-parser';
import type { NodeComponentProps } from '../../types/node-component';
export interface ListItemNodeData {
    type: 'list_item';
    children?: ParsedNode[];
    raw?: string;
}
export interface ListItemNodeProps extends NodeComponentProps<ListItemNodeData> {
    value?: number;
}
export declare function ListItemNode(props: ListItemNodeProps): import("octane/jsx-runtime").Octane.JSX.Element;
export default ListItemNode;
