// Generated by scripts/generate-tsrx-types.mjs.
import type { NodeComponentProps } from '../../types/node-component';
export declare function EmphasisNode(props: NodeComponentProps<{
    type: 'emphasis';
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export default EmphasisNode;
