// Generated by scripts/generate-tsrx-types.mjs.
import type { NodeComponentProps } from '../../types/node-component';
export declare function HighlightNode(props: NodeComponentProps<{
    type: 'highlight';
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export default HighlightNode;
