// Generated by scripts/generate-tsrx-types.mjs.
import type { NodeComponentProps } from '../../types/node-component';
export declare function FootnoteAnchorNode(props: NodeComponentProps<{
    type: 'footnote_anchor';
    id: string;
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export default FootnoteAnchorNode;
