// Generated by scripts/generate-tsrx-types.mjs.
import type { InfographicBlockNodeProps, MermaidBlockEvent } from '../../types/component-props';
export interface InfographicBlockNodeOctaneEvents {
    onCopy?: (code: string) => void;
    onExport?: (event: MermaidBlockEvent<{
        type: 'export';
    }>) => void;
    onOpenModal?: (event: MermaidBlockEvent<{
        type: 'open-modal';
    }>) => void;
    onToggleMode?: (target: 'preview' | 'source', event: MermaidBlockEvent<{
        type: 'toggle-mode';
        target: 'preview' | 'source';
    }>) => void;
}
export declare function InfographicBlockNode(rawProps: InfographicBlockNodeProps & InfographicBlockNodeOctaneEvents): import("octane/jsx-runtime").Octane.JSX.Element;
