// Generated by scripts/generate-tsrx-types.mjs.
import type { NodeComponentProps } from '../../types/node-component';
export declare function FallbackComponent(props: NodeComponentProps<{
    type: string;
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export default FallbackComponent;
