// Generated by scripts/generate-tsrx-types.mjs.
import type { NodeComponentProps } from '../../types/node-component';
export declare function StrongNode(props: NodeComponentProps<{
    type: 'strong';
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export default StrongNode;
