// Generated by scripts/generate-tsrx-types.mjs.
import type { ParsedNode } from 'stream-markdown-parser';
import type { NodeComponentProps } from '../../types/node-component';
export declare function HeadingNode(props: NodeComponentProps<{
    type: 'heading';
    level?: number;
    children?: ParsedNode[];
    attrs?: Record<string, string | boolean>;
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export default HeadingNode;
