// Generated by scripts/generate-tsrx-types.mjs.
import type { NodeComponentProps } from '../../types/node-component';
export declare function HardBreakNode(_props: NodeComponentProps<{
    type: 'hardbreak';
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export default HardBreakNode;
