// Generated by scripts/generate-tsrx-types.mjs.
import * as Octane from 'octane';
export interface VisibilityHandle {
    isVisible: () => boolean;
    whenVisible: Promise<void>;
    destroy: () => void;
}
export type RegisterViewportFn = (el: HTMLElement, opts?: {
    rootMargin?: string;
    threshold?: number;
}) => VisibilityHandle;
export interface ViewportPriorityProviderProps {
    getRoot: () => HTMLElement | null;
    enabled?: boolean;
    children: Octane.OctaneNode;
}
export declare function ViewportPriorityProvider({ getRoot, enabled, children }: ViewportPriorityProviderProps): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function useViewportPriority(): RegisterViewportFn;
