// Generated by scripts/generate-tsrx-types.mjs.
import type { ParsedNode } from 'stream-markdown-parser';
import type { NodeComponentProps } from '../../types/node-component';
export interface LinkNodeStyleProps {
    showTooltip?: boolean;
    color?: string;
    underlineHeight?: number;
    underlineBottom?: number | string;
    animationDuration?: number;
    animationOpacity?: number;
    animationTiming?: string;
    animationIteration?: string | number;
}
export declare function LinkNode(props: NodeComponentProps<{
    type: 'link';
    href: string;
    title: string | null;
    text: string;
    children?: ParsedNode[];
    loading?: boolean;
}> & LinkNodeStyleProps): import("octane/jsx-runtime").Octane.JSX.Element;
export default LinkNode;
