// Generated by scripts/generate-tsrx-types.mjs.
import type { HtmlPolicy, ParsedNode } from 'stream-markdown-parser';
import type { NodeComponentProps } from '../../types/node-component';
import * as Octane from 'octane';
export declare function HtmlInlineNode(props: NodeComponentProps<{
    type: 'html_inline';
    content: string;
    tag?: string;
    attrs?: [string, string | null][] | null;
    children?: ParsedNode[];
    loading?: boolean;
    autoClosed?: boolean;
}> & {
    htmlPolicy?: HtmlPolicy;
}): import("octane/jsx-runtime").Octane.JSX.Element | Octane.ElementDescriptor<Record<string, import("stream-markdown-parser").HtmlPropValue>>;
export default HtmlInlineNode;
