// Generated by scripts/generate-tsrx-types.mjs.
import type { CodeBlockNodeProps } from '../../types/component-props';
export interface CodeBlockPreviewPayload {
    node: CodeBlockNodeProps['node'];
    artifactType: 'text/html' | 'image/svg+xml';
    artifactTitle: string;
    id: string;
}
export interface CodeBlockNodeOctaneEvents {
    onCopy?: (code: string) => void;
    onPreviewCode?: (payload: CodeBlockPreviewPayload) => void;
}
export declare function CodeBlockNode(rawProps: CodeBlockNodeProps & CodeBlockNodeOctaneEvents): import("octane/jsx-runtime").Octane.JSX.Element;
export default CodeBlockNode;
