// Generated by scripts/generate-tsrx-types.mjs.
import * as Octane from 'octane';
export interface HtmlPreviewFrameProps {
    code: string;
    isDark?: boolean;
    htmlPreviewAllowScripts?: boolean;
    htmlPreviewSandbox?: string;
    onClose?: () => void;
    title?: string;
}
export declare function HtmlPreviewFrame(props: HtmlPreviewFrameProps): Octane.PortalDescriptor | null;
export default HtmlPreviewFrame;
