// Generated by scripts/generate-tsrx-types.mjs.
import type { PreCodeNodeProps } from '../../types/component-props';
export declare function PreCodeNode({ node, className, diffInline, showLineNumbers, style }: PreCodeNodeProps): import("octane/jsx-runtime").Octane.JSX.Element;
