// Generated by scripts/generate-tsrx-types.mjs.
import type { ParsedNode } from 'stream-markdown-parser';
import type { NodeComponentProps } from '../../types/node-component';
import * as Octane from 'octane';
export declare function ParagraphNode(props: NodeComponentProps<{
    type: 'paragraph';
    children?: ParsedNode[];
}>): Octane.ElementDescriptor<{}>;
export default ParagraphNode;
