// Generated by scripts/generate-tsrx-types.mjs.
import type { D2BlockNodeProps } from '../../types/component-props';
export declare function D2BlockNode(rawProps: D2BlockNodeProps): import("octane/jsx-runtime").Octane.JSX.Element;
