// Generated by scripts/generate-tsrx-types.mjs.
import type { ImageNodeProps } from '../../types/component-props';
export interface ImageNodeOctaneEvents {
    onLoad?: (src: string) => void;
    onError?: (src: string) => void;
    onClick?: (payload: [event: MouseEvent, src: string]) => void;
}
export declare function ImageNode(rawProps: ImageNodeProps & ImageNodeOctaneEvents): import("octane/jsx-runtime").Octane.JSX.Element | null;
export default ImageNode;
