// Generated by scripts/generate-tsrx-types.mjs.
import * as Octane from 'octane';
export type TooltipPlacement = 'top' | 'bottom' | 'left' | 'right';
export interface TooltipProps {
    visible: boolean;
    anchorEl: HTMLElement | null;
    content: string;
    placement?: TooltipPlacement;
    offset?: number;
    originX?: number | null;
    originY?: number | null;
    id?: string | null;
    isDark?: boolean | null;
}
export declare function Tooltip(props: TooltipProps): Octane.PortalDescriptor | null;
export default Tooltip;
