// Generated by scripts/generate-tsrx-types.mjs.
import type { ParsedNode } from 'stream-markdown-parser';
import type { NodeComponentProps } from '../../types/node-component';
export declare function AdmonitionNode(props: NodeComponentProps<{
    type: 'admonition';
    kind?: string;
    title?: string;
    children?: ParsedNode[];
    collapsible?: boolean;
    open?: boolean;
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export default AdmonitionNode;
