// Generated by scripts/generate-tsrx-types.mjs.
import type { NodeComponentProps } from '../../types/node-component';
export declare function StrikethroughNode(props: NodeComponentProps<{
    type: 'strikethrough';
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export default StrikethroughNode;
