// Generated by scripts/generate-tsrx-types.mjs.
import type { ParsedNode } from 'stream-markdown-parser';
import type { RenderContext, RenderNodeFn } from '../types';
export declare const BLOCK_LEVEL_TYPES: Set<string>;
export declare function tokenAttrsToProps(attrs?: [string, string | null][]): Record<string, string | true> | undefined;
export declare function renderNodeChildren(children: ParsedNode[] | undefined, ctx: RenderContext, prefix: string, renderNode: RenderNodeFn): unknown[] | null;
export declare function renderInline(children: ParsedNode[] | undefined, ctx: RenderContext, prefix: string, renderNode: RenderNodeFn): unknown[] | null;
