// Generated by scripts/generate-tsrx-types.mjs.
import type { TableRowNode } from 'stream-markdown-parser';
import type { NodeComponentProps } from '../../types/node-component';
export declare function TableNode(props: NodeComponentProps<{
    type: 'table';
    header?: TableRowNode;
    rows?: TableRowNode[];
    loading?: boolean;
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export default TableNode;
