// Generated by scripts/generate-tsrx-types.mjs.
import type { NodeComponentProps } from '../../types/node-component';
export declare function EmojiNode(props: NodeComponentProps<{
    type: 'emoji';
    name: string;
    markup?: string;
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export default EmojiNode;
